/// TransactionModel — in-memory model for a cashier transaction.
///
/// UUID is generated by the caller (e.g. `const Uuid().v4()`) and passed in;
/// it is NOT generated inside this constructor.
class TransactionModel {
  final String uuid;
  final List<Map<String, dynamic>> items; // [{product_id, qty, price}]
  final double discount;
  final String paymentMethod;
  final double total;
  final int? branchId;
  final DateTime createdAt;

  const TransactionModel({
    required this.uuid,
    required this.items,
    required this.discount,
    required this.paymentMethod,
    required this.total,
    this.branchId,
    required this.createdAt,
  });

  /// Maps to the `POST /api/transactions` request body.
  Map<String, dynamic> toApiPayload() {
    return <String, dynamic>{
      'items': items,
      'discount': discount,
      'payment_method': paymentMethod,
      'payment_amount': total,
      if (branchId != null) 'branch_id': branchId,
    };
  }

  /// Serialises to a plain map for storage in [OfflineTransactionEntry.payload].
  Map<String, dynamic> toHiveMap() {
    return <String, dynamic>{
      'uuid': uuid,
      'items': items,
      'discount': discount,
      'payment_method': paymentMethod,
      'total': total,
      'branch_id': branchId,
      'created_at': createdAt.toIso8601String(),
    };
  }

  /// Reconstructs a [TransactionModel] from a map previously produced by
  /// [toHiveMap].
  factory TransactionModel.fromHiveMap(Map map) {
    final rawItems = map['items'] as List;
    final items = rawItems
        .map((e) => Map<String, dynamic>.from(e as Map))
        .toList();

    return TransactionModel(
      uuid: map['uuid'] as String,
      items: items,
      discount: (map['discount'] as num).toDouble(),
      paymentMethod: map['payment_method'] as String,
      total: (map['total'] as num).toDouble(),
      branchId: map['branch_id'] as int?,
      createdAt: DateTime.parse(map['created_at'] as String),
    );
  }
}
